WITH Ultimos AS (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY CEDULA ORDER BY TIME_STAMP DESC) AS rn
    FROM charlieserver-281513.produbanco_dev.diferencias
),
PagoInferido AS (
    SELECT CEDULA,
           MAX(CASE 
                   WHEN TIPO_CAMBIO = 'PAGO_INFERIDO' THEN 'PAGO_INFERIDO'
                   ELSE NULL 
               END) AS SENT_PAGO
    FROM charlieserver-281513.produbanco_dev.diferencias
    GROUP BY CEDULA
),
MontoPagoTotal AS (
    SELECT CEDULA, SUM(MONTO_PAGO) AS TOTAL_MONTO_PAGO
    FROM charlieserver-281513.produbanco_dev.diferencias
    GROUP BY CEDULA
),
AumentoDeudaTotal AS (
    SELECT CEDULA, SUM(AUMENTO_DEUDA) AS TOTAL_AUMENTO_DEUDA
    FROM charlieserver-281513.produbanco_dev.diferencias
    GROUP BY CEDULA
),
ClientInteraction AS (
    SELECT DISTINCT CEDULA, 'CON INTERACCION' AS INTERACCION
    FROM charlieserver-281513.produbanco_dev.client_intents
)
SELECT 
    u.CEDULA,
    u.PAGO_MINIMO AS ULTIMO_PAGO_MINIMO,
    u.PAGO_MINIMO_INICIAL AS ULTIMO_PAGO_MINIMO_INICIAL,
    u.PAGO_MINIMO_ULTIMO AS ULTIMO_PAGO_MINIMO_ULTIMO,
    u.PAGO_MINIMO_PREVIO AS ULTIMO_PAGO_MINIMO_PREVIO,
    u.DIFERENCIA AS ULTIMA_DIFERENCIA,
    u.TIPO_CAMBIO AS ULTIMO_TIPO_CAMBIO,
    u.DIAS_MORA AS ULTIMOS_DIAS_MORA,
    u.CALIFICACION AS ULTIMA_CALIFICACION,
    u.RESPOND AS ULTIMO_RESPOND,
    u.CAMPANIA AS ULTIMA_CAMPANIA,
    u.BUCKET AS ULTIMO_BUCKET,
    u.ESTADO_CONVENIO AS ULTIMO_ESTADO_CONVENIO,
    u.TIPO_GESTION AS ULTIMO_TIPO_GESTION,
    COALESCE(mp.TOTAL_MONTO_PAGO, 0) AS TOTAL_MONTO_PAGO,
    COALESCE(ad.TOTAL_AUMENTO_DEUDA, 0) AS TOTAL_AUMENTO_DEUDA,
    COALESCE(ci.INTERACCION, 'SIN INTERACCION') AS INTERACCION,
    COALESCE(p.SENT_PAGO, 'NO PAGO INFERIDO') AS SENT_PAGO
FROM Ultimos u
LEFT JOIN ClientInteraction ci 
    ON u.CEDULA = ci.CEDULA
LEFT JOIN PagoInferido p 
    ON u.CEDULA = p.CEDULA
LEFT JOIN MontoPagoTotal mp 
    ON u.CEDULA = mp.CEDULA
LEFT JOIN AumentoDeudaTotal ad 
    ON u.CEDULA = ad.CEDULA
WHERE u.rn = 1
