crediflores:
  outputs:
    dev:
      dataset: crediflores_dev
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: /dbt/gcp/credencial_charlie.json
      location: US
      method: service-account
      priority: interactive
      project: charlieserver-281513
      threads: 1
      type: bigquery
    prod:
      dataset: crediflores_prod
      job_execution_timeout_seconds: 300
      job_retries: 3
      keyfile: /dbt/gcp/credencial_charlie.json
      location: US
      method: service-account
      priority: interactive
      project: charlieserver-281513
      threads: 4
      type: bigquery
  target: prod