

produbanco:
  outputs:
    dev:
      dataset: PRODUBANCO_DEV
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: /dbt/gcp/dbt_test.json
      location: US
      method: service-account
      priority: interactive
      project: memorialtechnologies-245614
      threads: 1
      type: bigquery
    prod:
      dataset: PRODUBANCO_PROD
      job_execution_timeout_seconds: 300
      job_retries: 3
      keyfile: /dbt/gcp/dbt_test.json
      location: US
      method: service-account
      priority: interactive
      project: memorialtechnologies-245614
      threads: 4
      type: bigquery
  target: dev
  