WITH base_data AS (
  SELECT 
    (CONCAT(CAST(A.cedula AS STRING), '-', CAST(B.TARJETA_DIG AS STRING))) AS UNIQUE_ID,
    CAST(A.cedula AS STRING) AS CEDULA,
    CONCAT('57', CAST(A.celular AS STRING)) AS CELULAR,
    CONCAT(TRIM(A.nombre), ' ', TRIM(A.apellido)) AS NOMBRE_COMPLETO,
    CAST(B.DIRECCION AS STRING) AS DIRECCION,

    {{ parse_money('B.VALOR_TOTAL_DEUDA') }} AS VALOR_TOTAL_DEUDA,
    {{ parse_money('B.SALDO_CAPITAL') }} AS SALDO_CAPITAL,
    {{ parse_money('B.PAGO_MINIMO') }} AS PAGO_MINIMO,

    GREATEST(
      COALESCE(SAFE_CAST(SAFE_CAST(B.DIAS_MORA AS NUMERIC) AS INT64), 0),
      0
    ) AS DIAS_MORA,
    CAST(B.TARJETA AS INT64) AS TARJETA,
    CAST(B.MARCA AS STRING) AS MARCA,
    CAST(B.CALIFICACION AS STRING) AS CALIFICACION,
    CAST(B.TARJETA_DIG AS INT64) AS TARJETA_DIG,
    CAST(B.TIPO_OPERACION AS STRING) AS TIPO_OPERACION,
    {{ parse_date_safe('B.FECHA_CORTE') }} AS FECHA_CORTE,
    CAST(B.BUCKET AS STRING) AS BUCKET,
    CAST(B.ESTADO_PRD AS STRING) AS ESTADO_PRD,
    {{ parse_date_safe('B.FECHA_PAGO') }} AS FECHA_PAGO,
    CAST(B.CAMPANIA AS STRING) AS CAMPANIA,
    CAST(B.ESTADO_CONVENIO AS STRING) AS ESTADO_CONVENIO,

    {{ parse_money('B.CAP_VENCIDO_CV') }} AS CAP_VENCIDO_CV,
    {{ parse_money('B.INTERESES') }} AS INTERESES,
    {{ parse_money('B.CALCULO_MORA') }} AS CALCULO_MORA,
    {{ parse_money('B.SEG_DE_VIDA_CV') }} AS SEG_DE_VIDA_CV,
    {{ parse_money('B.SALDO_CAPITAL_C') }} AS SALDO_CAPITAL_C,
    {{ parse_money('B.P_CONDONACION_CAPITAL') }} AS P_CONDONACION_CAPITAL,
    {{ parse_money('B.VR_MAX_COND_CAP') }} AS VR_MAX_COND_CAP,
    {{ parse_money('B.INTERESES_CTES') }} AS INTERESES_CTES,
    {{ parse_money('B.P_COND_INT') }} AS P_COND_INT,
    {{ parse_money('B.VR_MAX_COND_INT') }} AS VR_MAX_COND_INT,
    {{ parse_money('B.INTERESES_MORA') }} AS INTERESES_MORA,
    {{ parse_money('B.P_COND_INT_1') }} AS P_COND_INT_1,
    {{ parse_money('B.VR_MAX_COND_INT_M') }} AS VR_MAX_COND_INT_M,
    {{ parse_money('B.VR_MAX_COND') }} AS VR_MAX_COND,
    {{ parse_money('B.TOTAL_RECUP_CREDIFLORES') }} AS TOTAL_RECUP_CREDIFLORES,
    {{ parse_money('B.VR_HONORARIOS') }} AS VR_HONORARIOS,
    {{ parse_money('B.VR_HONORARIOS_PAGO_VALOR_TOTAL_DEUDA_') }} AS VR_HONORARIOS_PAGO_VALOR_TOTAL_DEUDA_,
    {{ parse_money('B.VR_HONORARIOS_PAGO_VALOR_TOTAL_DEUDA_1') }} AS VR_HONORARIOS_PAGO_VALOR_TOTAL_DEUDA_1,

    {{ parse_money('B.VL_MIN_PAGO') }} AS VL_MIN_PAGO,
    {{ parse_money('B.ANO_CASTIGO') }} AS ANO_CASTIGO,
    {{ parse_money('B.F_CASTIGO') }} AS F_CASTIGO,

    CAST(B.INSTANCIA_DE_COBRO AS STRING) AS INSTANCIA_DE_COBRO,
    TIMESTAMP(B.TIME_STAMP) AS TIME_STAMP,
    CAST(A.nombre AS STRING) AS NOMBRE,
    CAST(A.apellido AS STRING) AS APELLIDO,
    SAFE_CAST(FLOOR(A.edad) AS INT64) AS EDAD,
    SAFE_CAST(FLOOR(A.campana) AS INT64) AS CAMPANA,

    CASE 
      WHEN SAFE_CAST(B.CAMPANIA AS INT64) = 0 THEN 0
      WHEN B.ESTADO_PRD = 'ACTIVO' THEN 1
      WHEN B.ESTADO_PRD = 'CASTIGADO' THEN 2
      ELSE NULL
    END AS RESPOND,

    0 AS POLITICA,
    0 AS SESION,
    CAST("2023-01-01 08:00:00" AS TIMESTAMP) AS SESSION_TIME,
    0 AS AUX_SOLUCION,
    CURRENT_DATE() AS FECHA_PROCESO,

    ROW_NUMBER() OVER (
      PARTITION BY A.cedula 
      ORDER BY {{ parse_money('B.VALOR_TOTAL_DEUDA') }} DESC
    ) AS rn

FROM {{ source('raw_data', 'DATA_WAREHAUSE_CLEAN') }}   AS A
JOIN {{ source('raw_data', 'DATA_WAREHAUSE_BL_COBRANZA') }} AS B
  ON A.cedula       = SAFE_CAST(B.CEDULA      AS INT64)
 AND A.tarjeta_dig = SAFE_CAST(B.TARJETA_DIG AS INT64)


  UNION ALL

  SELECT
    "1750728626-987654" AS UNIQUE_ID,
    "1750728626" AS CEDULA,
    "593999372880" AS CELULAR,
    "Diana Cuenca" AS NOMBRE_COMPLETO,
    "Av. Siempre Viva 742" AS DIRECCION,
    120000.00 AS VALOR_TOTAL_DEUDA,
    80000.00 AS SALDO_CAPITAL,
    40000.00 AS PAGO_MINIMO,
    15 AS DIAS_MORA,
    1 AS TARJETA,
    "MASTERCARD" AS MARCA,
    "B" AS CALIFICACION,
    987654 AS TARJETA_DIG,
    "ROTATIVO" AS TIPO_OPERACION,
    DATE("2024-06-01") AS FECHA_CORTE,
    "BUCKET_2" AS BUCKET,
    "ACTIVO" AS ESTADO_PRD,
    DATE("2024-06-15") AS FECHA_PAGO,
    "CAMPAÑA TEST" AS CAMPANIA,
    "AL DIA" AS ESTADO_CONVENIO,
    5000 AS CAP_VENCIDO_CV,
    1200 AS INTERESES,
    300 AS CALCULO_MORA,
    100 AS SEG_DE_VIDA_CV,
    70000 AS SALDO_CAPITAL_C,
    2000 AS P_CONDONACION_CAPITAL,
    2500 AS VR_MAX_COND_CAP,
    600 AS INTERESES_CTES,
    150 AS P_COND_INT,
    180 AS VR_MAX_COND_INT,
    220 AS INTERESES_MORA,
    100 AS P_COND_INT_1,
    110 AS VR_MAX_COND_INT_M,
    330 AS VR_MAX_COND,
    7500 AS TOTAL_RECUP_CREDIFLORES,
    50000 AS VR_HONORARIOS,
    300 AS VR_HONORARIOS_PAGO_VALOR_TOTAL_DEUDA_,
    290 AS VR_HONORARIOS_PAGO_VALOR_TOTAL_DEUDA_1,
    35000 AS VL_MIN_PAGO,
    2020 AS ANO_CASTIGO,
    20200615 AS F_CASTIGO,
    "EXTRAJUDICIAL" AS INSTANCIA_DE_COBRO,
    CURRENT_TIMESTAMP() AS TIME_STAMP,
    "Diana" AS NOMBRE,
    "Cuenca" AS APELLIDO,
    26 AS EDAD,
    1 AS CAMPANA,
    1 AS RESPOND,
    0 AS POLITICA,
    0 AS SESION,
    CAST("2023-01-01 08:00:00" AS TIMESTAMP) AS SESSION_TIME,
    0 AS AUX_SOLUCION,
    CURRENT_DATE() AS FECHA_PROCESO,
    1 AS rn
)

SELECT * FROM base_data
WHERE rn = 1
