generali:
  outputs:
    dev:
      dataset: generali
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: /opt/airflow/dbt/GENERALI/gcp/dbt_test.json
      location: US
      method: service-account
      priority: interactive
      project: memorialtechnologies-245614
      threads: 1
      type: bigquery
    prod:
      dataset: generali
      job_execution_timeout_seconds: 300
      job_retries: 3
      keyfile: /opt/airflow/dbt/GENERALI/gcp/dbt_test.json
      location: US
      method: service-account
      priority: interactive
      project: memorialtechnologies-245614
      threads: 4
      type: bigquery
  target: dev  # Default environment
